---
- hosts: webservers
  tasks:
  - name: Download root directory
    file:
      path=/root/Downloads
      owner=root
      group=root
      mode=0755
      state=directory

  - name: Download mysql deb file
    get_url:
      url: https://repo.mysql.com/mysql-apt-config_0.8.26-1_all.deb
      dest: "/root/Downloads"
      mode: 0440

  - name: Install mysql repo
    apt: "deb=/root/Downloads/mysql-apt-config_0.8.26-1_all.deb"

  - name: Install mysql
    apt: name=mysql-server update_cache=yes state=present

  - name: Install pymysql
    apt: name=python3-mysqldb update_cache=yes state=latest

  - name: Root login file
    copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
        [client]
        user=root
        password=qwerty


  - name: Loome kasutaja parooliga koos kõikide õigustega
    mysql_user:
      name: root
      password: qwerty
      login_user: root
      login_password: qwerty
      priv: '*.*:ALL,GRANT'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock


  - name: Mysql restart
    service: name=mysql state=restarted
